export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const RESET_PRICE = 'RESET_PRICE';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';
